name: flutter_clean_code_example
description: TDD Clean Code Architecture Example.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.0
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6
  # Local cache
  shared_preferences: ^2.1.2
  build_runner: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true
